name: Python CI

on:
  push:
    branches:
      - main  # Adjust this to match the branch you're pushing to
  pull_request:
    branches:
      - main  # Adjust this to match the target branch of your pull request

jobs:
  build:
    runs-on: ubuntu-latest  # You can choose a different OS if needed

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # This checks out the code from the repository

      - name: Set up Python
        uses: actions/setup-python@v4  # This sets up Python in the CI environment
        with:
          python-version: '3.10'  # Specify the Python version you want to use

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies from requirements.txt

      - name: Run tests
        run: |
          python -m unittest discover -s . -p "test_*.py"  # Runs tests in files matching test_*.py
